### ISSUE TITLE
Integration in Contao 3

### ISSUE THREAD

**Issue by danielritter** [psi-4ward/Formular#1]
Danke für die Erweiterung. So etwas habe ich schon immer in Contao vermisst. Wäre es möglich, diese Erweiterung für den Contao-Core zur Verfügung zu stellen, also sofern Leo das möchte? Das wäre definitiv eine Bereicherung für Contao und für die Eigenentwicklung.

**Comment by psi-4ward** [comment]
Bitte, es gibt ein Ticket im Contao-Tracker aber dies hab leider nicht ich zu entscheiden.

**Comment by danielritter** [comment]
Crazy, bist du schnell. :) Ah oke, habe ich nicht gesehen. Hast du eventuell gerade den Link dazu?

**Comment by psi-4ward** [comment]
https://github.com/contao/core/issues/3768

**Comment by danielritter** [comment]
Danke!
